--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: glams-9
  namespace: jenkins
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: glams
  template: 
    metadata: 
      labels: 
        run: glams
    spec: 
      containers: 
        - 
          image: sainikhil1999/glams
          name: glams-9
          ports: 
            - 
              containerPort: 5000
