--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: glams
  name: G7
  namespace: jenkins
spec: 
  ports: 
    - 
      name: http
      port: 5000
      protocol: TCP
      targetPort: 80
  selector: 
    run: glams
  type: NodePort
